export const TOGGLE_PLAY_PAUSE = 'TOGGLE_PLAY_PAUSE';
export const SET_TEMPO = 'SET_TEMPO';
export const INCREMENT_TEMPO = 'INCREMENT_TEMPO';
export const DECREMENT_TEMPO = 'DECREMENT_TEMPO';
export const SET_METER = 'SET_METER';
export const SET_MASTER_VOLUME = 'SET_MASTER_VOLUME';
export const SET_ACCENT_VOLUME = 'SET_ACCENT_VOLUME';
export const SET_QUARTER_VOLUME = 'SET_QUARTER_VOLUME';
export const SET_EIGTH_VOLUME = 'SET_EIGTH_VOLUME';
export const SET_SIXTEENTH_VOLUME = 'SET_SIXTEENTH_VOLUME';
export const SET_TRIPLET_VOLUME = 'SET_TRIPLET_VOLUME';

export const SAVE_APP_STATE_ACTIONS = [
  SET_TEMPO,
  INCREMENT_TEMPO,
  DECREMENT_TEMPO,
  SET_METER,
  SET_MASTER_VOLUME,
  SET_ACCENT_VOLUME,
  SET_QUARTER_VOLUME,
  SET_EIGTH_VOLUME,
  SET_SIXTEENTH_VOLUME,
  SET_TRIPLET_VOLUME
];

export const DEFAULT_TEMPO = 120;
export const DEFAULT_METER = 4;
export const DEFAULT_MASTER_VOLUME = 0.5;
export const DEFAULT_ACCENT_VOLUME = 1;
export const DEFAULT_QUARTER_VOLUME = 0.75;
export const DEFAULT_EIGTH_VOLUME = 0;
export const DEFAULT_SIXTEENTH_VOLUME = 0;
export const DEFAULT_TRIPLET_VOLUME = 0;
